
	import HelloWorld from './hello-world.js';
import { Component1, Component2 } from './components.js';
	
	export default () => (
		<div className='autogenerated-post'>
			<p>A classmate and I developed an app that FamilyTree could use to view where the majority of their census records are based.</p>
<p>In the end of the class we won a $500 gift certificate to Microsoft Store for placing second in the competition.</p>
		</div>
	)