
	
	
	export default () => (
		<div className='autogenerated-post'>
			<p>After starting and not finishing too many overly ambitious projects.  I decided to build a simple web app where a user could login with facebook, select a photo, and then view that photo with a mustache on it.</p>
<p><img src="/static/images/mustache-demo.gif" alt="Demo of Put A Mustache On Your Face .com" /></p>
<h3 id="technology-used">Technology Used</h3>
<p>To build this app I created a front end server to host the user interface, and a backend API server to supply the user interface with data.</p>
<p>I built the front end server with node.js, React JS, Next.js, and Semantic UI.  By using Next.js I was able to get up and running with a server side rendered app quickly.</p>
<p>I wrote the backend API in Python.  I used flask and graphene to create a graphql server, and I used <a href="https://github.com/ageitgey/face_recognition">https://github.com/ageitgey/face_recognition</a> for the face recognition.  I used Dynamodb to store user data, and Amazon s3 to store images.</p>
<p>To make deployments simple, I wrapped both of the servers in docker containers and deployed those containers to Elastic Beanstalk on AWS.</p>
		</div>
	)