
	
	
	export default () => (
		<div className='autogenerated-post'>
			<p>After my friend and I worked on their home page, Whistic came back looking to design and build another page of their application.</p>
<p>My friend and I came up with designs, iterated over those designs with a contact at Whistic and eventually built the page using Bootstrap 3.</p>
		</div>
	)