
	import enhancePage from './../../hocs/enhancePage';
	import Layout from './../../components/Layout';
	import PostContent from './../../components/PostContent';
	import NextPost from './../../components/NextPost';
	import Link from 'next/link'
	import Container from './../../components/Container';
	
	
	
	export default enhancePage(({url}) => (
		<Layout url={url}>
		<div className='autogenerated-post'>
			<h1 id="jeffrey-young">Jeffrey Young</h1>
<h2 id="front-end-software-engineer">Front End Software Engineer</h2>
<blockquote>
  <p><a href="jeffreytyoung1990@gmail.com">jeffreytyoung1990@gmail.com</a>  </p>
</blockquote>
<hr />
<h2 id="experience">Experience</h2>
<p><strong>Adobe</strong><br />
  <em>Front End Software Engineer</em><br />
  Aug 2016-Present<br />
  React.js, Angular.js, Node.js, PHP</p>
<p><strong>Qualtrics</strong><br />
  <em>Full Stack Software Engineer</em><br />
  Jan 2015-April 2016<br />
  Java Spring, Python, Angular.js, PHP</p>
<hr />
<h2 id="education">Education</h2>
<p><strong>Brigham Young University</strong><br />
 <em>Computer Science</em><br />
 Aug 2009-April 2016</p>
		</div>
		</Layout>
	))